#   conda env create -f environment.yml
#   conda activate ml-exercise
name: ml-exercise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - ipykernel
  - tqdm
